//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Utilities;

    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Attachment = new HashSet<Attachment>();
            CreatedOn = DateTime.Now;
            ModifiedOn = DateTime.Now;
            DateTime = DateTime.Now;
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter task title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Please enter task description")]
        [StringLength(1500,MinimumLength =10)]
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
        public int EmployeeId { get; set; }
        [TimeValidation]
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual Users Users { get; set; }
    }
}
